name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ '25', '26-ea' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -Djunit.jupiter.execution.parallel.enabled=false

      - name: Verify class file versions
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $VERSION"
          
          JAR_FILE="target/for-comprehension4j-$VERSION.jar"
          
          jar tf "$JAR_FILE" | grep '\.class$' | grep -vE 'module-info|package-info' | while read -r f; do
            class_name="${f%.class}"
            class_name="${class_name//\//.}"  # replace / with .
          
            major=$(javap -verbose -cp "$JAR_FILE" "$class_name" | grep "major version" | awk '{print $3}')
          
            echo "$f -> major version $major"
          
            if [ "$major" -gt 52 ]; then
              echo "ERROR: $f compiled with Java version $major (incompatible with Java 8)"
              exit 1
            fi
          done

  deploy-snapshot:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Deploy Snapshot
        run: mvn -B --no-transfer-progress -Psonatype-oss-release -DskipTests=true deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

